

export const requirementsData = [
    {
        id: 1,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 2,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 3,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 4,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 5,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 6,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 7,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 8,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 9,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 10,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 12,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 13,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 14,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
    {
        id: 15,
        requirementCode: "A-1",
        requestedBy: "John Doe",
        organization: "GPC",
        department: "Tech",
        unit: "Software",
        date: "2024-12-01",
        time: "08:00",
        assignedTo: "Johan Blake",
        category: "Software update",
        detail: "Just update software bug",
        priority: 10,
        status: "in progress",
        history: []       
    },
]